# SupplyPrescript

# Sprint 3 - Data Preprocessing

## Objective

The objective of this notebook is to clean and transform the logistics dataset into a machine-learning-ready dataset.

The preprocessing steps include:

- Loading the dataset
- Converting data types
- Feature engineering
- Encoding categorical variables
- Saving the processed dataset/

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/raw/logistics_dataset.csv")

df.head()

,Shipment_ID,Date,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred
0,SC-10000,2025-10-16,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1
1,SC-10001,2024-04-24,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1
2,SC-10002,2024-01-26,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0
3,SC-10003,2024-10-08,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1
4,SC-10004,2024-09-07,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1

In [3]:
df_processed = df.copy()

In [4]:
df_processed.dtypes

Shipment_ID                      str
Date                             str
Origin_Port                      str
Destination_Port                 str
Transport_Mode                   str
Product_Category                 str
Distance_km                  float64
Weight_MT                    float64
Fuel_Price_Index             float64
Geopolitical_Risk_Score      float64
Weather_Condition                str
Carrier_Reliability_Score    float64
Lead_Time_Days               float64
Disruption_Occurred            int64
dtype: object

In [5]:
df_processed["Date"] = pd.to_datetime(df_processed["Date"])

df_processed.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Shipment_ID                5000 non-null   str
 1   Date                       5000 non-null   datetime64[us]
 2   Origin_Port                5000 non-null   str
 3   Destination_Port           5000 non-null   str
 4   Transport_Mode             5000 non-null   str
 5   Product_Category           5000 non-null   str
 6   Distance_km                5000 non-null   float64
 7   Weight_MT                  5000 non-null   float64
 8   Fuel_Price_Index           5000 non-null   float64
 9   Geopolitical_Risk_Score    5000 non-null   float64
 10  Weather_Condition          5000 non-null   str
 11  Carrier_Reliability_Score  5000 non-null   float64
 12  Lead_Time_Days             5000 non-null   float64
 13  Disruption_Occurred        5000 non-null   int64
dtypes: datetime64[us](1), float64(6), int64(1), str(6)
memory usage: 547.0 KB

In [6]:
df_processed["Year"] = df_processed["Date"].dt.year
df_processed["Month"] = df_processed["Date"].dt.month
df_processed["Day"] = df_processed["Date"].dt.day
df_processed["DayOfWeek"] = df_processed["Date"].dt.day_name()

In [7]:
df_processed.head()

,Shipment_ID,Date,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred,Year,Month,Day,DayOfWeek
0,SC-10000,2025-10-16,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1,2025,10,16,Thursday
1,SC-10001,2024-04-24,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1,2024,4,24,Wednesday
2,SC-10002,2024-01-26,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0,2024,1,26,Friday
3,SC-10003,2024-10-08,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1,2024,10,8,Tuesday
4,SC-10004,2024-09-07,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1,2024,9,7,Saturday

In [8]:
df_processed.drop("Date", axis=1, inplace=True)

In [9]:
df_processed.head()

,Shipment_ID,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred,Year,Month,Day,DayOfWeek
0,SC-10000,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1,2025,10,16,Thursday
1,SC-10001,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1,2024,4,24,Wednesday
2,SC-10002,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0,2024,1,26,Friday
3,SC-10003,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1,2024,10,8,Tuesday
4,SC-10004,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1,2024,9,7,Saturday

In [10]:
df_processed.select_dtypes(include="object").columns

C:\Users\Utpreksha Kashyap\AppData\Local\Temp\ipykernel_2712\4027151476.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_processed.select_dtypes(include="object").columns

Index(['Shipment_ID', 'Origin_Port', 'Destination_Port', 'Transport_Mode',
       'Product_Category', 'Weather_Condition', 'DayOfWeek'],
      dtype='str')

In [11]:
df_processed.drop("Shipment_ID", axis=1, inplace=True)

In [12]:
df_processed.head()

,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred,Year,Month,Day,DayOfWeek
0,Singapore,Los Angeles,Rail,Textiles,5930.83,197.42,2.43,5.0,Hurricane,0.865,41.39,1,2025,10,16,Thursday
1,Singapore,Shanghai,Rail,Automotive,14285.36,237.24,2.30,7.5,Storm,0.592,40.92,1,2024,4,24,Wednesday
2,Rotterdam,Los Angeles,Rail,Perishables,11113.91,427.42,1.78,5.6,Rain,0.673,11.54,0,2024,1,26,Friday
3,Busan,Hamburg,Rail,Electronics,9180.55,170.66,3.20,0.8,Hurricane,0.832,53.13,1,2024,10,8,Tuesday
4,Busan,Singapore,Air,Perishables,2762.27,434.96,2.77,1.9,Fog,0.741,0.50,1,2024,9,7,Saturday

In [13]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

categorical_columns = [
    "Origin_Port",
    "Destination_Port",
    "Transport_Mode",
    "Product_Category",
    "Weather_Condition",
    "DayOfWeek"
]

for col in categorical_columns:
    df_processed[col] = label_encoder.fit_transform(df_processed[col])

In [14]:
df_processed.head()

,Origin_Port,Destination_Port,Transport_Mode,Product_Category,Distance_km,Weight_MT,Fuel_Price_Index,Geopolitical_Risk_Score,Weather_Condition,Carrier_Reliability_Score,Lead_Time_Days,Disruption_Occurred,Year,Month,Day,DayOfWeek
0,7,4,1,4,5930.83,197.42,2.43,5.0,2,0.865,41.39,1,2025,10,16,4
1,7,7,1,0,14285.36,237.24,2.30,7.5,4,0.592,40.92,1,2024,4,24,6
2,5,4,1,2,11113.91,427.42,1.78,5.6,3,0.673,11.54,0,2024,1,26,0
3,1,3,1,1,9180.55,170.66,3.20,0.8,2,0.832,53.13,1,2024,10,8,5
4,1,8,0,2,2762.27,434.96,2.77,1.9,1,0.741,0.50,1,2024,9,7,2

In [15]:
df_processed.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Origin_Port                5000 non-null   int64
 1   Destination_Port           5000 non-null   int64
 2   Transport_Mode             5000 non-null   int64
 3   Product_Category           5000 non-null   int64
 4   Distance_km                5000 non-null   float64
 5   Weight_MT                  5000 non-null   float64
 6   Fuel_Price_Index           5000 non-null   float64
 7   Geopolitical_Risk_Score    5000 non-null   float64
 8   Weather_Condition          5000 non-null   int64
 9   Carrier_Reliability_Score  5000 non-null   float64
 10  Lead_Time_Days             5000 non-null   float64
 11  Disruption_Occurred        5000 non-null   int64
 12  Year                       5000 non-null   int32
 13  Month                      5000 non-null   int32
 14  Day                        5000 non-null   int32
 15  DayOfWeek                  5000 non-null   int64
dtypes: float64(6), int32(3), int64(7)
memory usage: 566.5 KB

In [16]:
import os

os.makedirs("../data/processed", exist_ok=True)

df_processed.to_csv(
    "../data/processed/cleaned_logistics_dataset.csv",
    index=False
)

In [17]:
import os

os.listdir("../data/processed")

['cleaned_logistics_dataset.csv']

# Preprocessing Summary

## Completed Tasks

- Converted Date to datetime
- Created Year, Month, Day, and DayOfWeek features
- Removed Shipment_ID
- Encoded categorical features
- Saved the cleaned dataset